version: '3.9'

services:
  api_service:
    build:
      context: .
      dockerfile: dockerfile_api_service
    container_name: api_service
    command: python src/api/main.py
    networks:
      - app_network 

  frontend:
    build:
      context: .
      dockerfile: dockerfile_app_service
    container_name: gradio_app
    command: tail -f /dev/null
    ports:
      - "5050:8000"  
    networks:
      - app_network  

networks:
  app_network:
    driver: bridge
